package com.fileshare.util;

import com.fileshare.exception.TokenExpiredException;
import com.fileshare.exception.InvalidTokenException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

/**
 * Generates and validates HMAC-SHA256 signed download tokens.
 *
 * Token format (restart-safe — no DB lookup required for validation):
 *   payload = "{fileUploadId}|{s3Key}|{expireEpochSeconds}|v1"
 *   signature = HMAC-SHA256(payload, HMAC_SECRET)
 *   token = base64url(payload) + "." + base64url(signature)
 *
 * The HMAC_SECRET is injected via environment variable so any service replica
 * with the same secret can verify tokens generated by any other replica.
 */
@Component
@Slf4j
public class HmacSignatureUtil {

    private static final String ALGORITHM = "HmacSHA256";
    private static final String VERSION = "v1";
    private static final String DELIMITER = "|";

    private final byte[] secretBytes;

    public HmacSignatureUtil(@Value("${app.hmac.secret}") String secret) {
        this.secretBytes = secret.getBytes(StandardCharsets.UTF_8);
    }

    /**
     * Creates a signed download token.
     *
     * @param fileUploadId The UUID of the file upload
     * @param s3Key        The S3 object key (included to prevent token reuse across files)
     * @param expiresAt    Epoch second when the token expires
     * @return A URL-safe token string
     */
    public String createToken(UUID fileUploadId, String s3Key, long expiresAt) {
        String payload = buildPayload(fileUploadId.toString(), s3Key, expiresAt);
        String payloadEncoded = base64UrlEncode(payload.getBytes(StandardCharsets.UTF_8));
        String signature = computeSignature(payload);
        return payloadEncoded + "." + signature;
    }

    /**
     * Validates a signed token and returns the parsed claims if valid.
     * Throws {@link InvalidTokenException} or {@link TokenExpiredException} if invalid.
     *
     * @param token The token string to validate
     * @return Parsed {@link TokenClaims}
     */
    public TokenClaims validateToken(String token) {
        String[] parts = token.split("\\.", 2);
        if (parts.length != 2) {
            throw new InvalidTokenException("Malformed token structure");
        }

        String payloadDecoded;
        try {
            payloadDecoded = new String(
                    Base64.getUrlDecoder().decode(parts[0]),
                    StandardCharsets.UTF_8
            );
        } catch (IllegalArgumentException e) {
            throw new InvalidTokenException("Malformed token encoding");
        }

        // Constant-time comparison to prevent timing side-channel attacks
        String expectedSignature = computeSignature(payloadDecoded);
        if (!constantTimeEquals(parts[1], expectedSignature)) {
            throw new InvalidTokenException("Invalid token signature");
        }

        String[] fields = payloadDecoded.split("\\|", 4);
        if (fields.length != 4) {
            throw new InvalidTokenException("Malformed token payload");
        }

        long expiresAt;
        try {
            expiresAt = Long.parseLong(fields[2]);
        } catch (NumberFormatException e) {
            throw new InvalidTokenException("Invalid token expiry format");
        }

        if (Instant.now().getEpochSecond() > expiresAt) {
            throw new TokenExpiredException("Download link has expired");
        }

        return new TokenClaims(UUID.fromString(fields[0]), fields[1], expiresAt, fields[3]);
    }

    private String buildPayload(String fileUploadId, String s3Key, long expiresAt) {
        return fileUploadId + DELIMITER + s3Key + DELIMITER + expiresAt + DELIMITER + VERSION;
    }

    private String computeSignature(String payload) {
        try {
            Mac mac = Mac.getInstance(ALGORITHM);
            mac.init(new SecretKeySpec(secretBytes, ALGORITHM));
            byte[] hmacBytes = mac.doFinal(payload.getBytes(StandardCharsets.UTF_8));
            return base64UrlEncode(hmacBytes);
        } catch (Exception e) {
            throw new RuntimeException("Failed to compute HMAC signature", e);
        }
    }

    private String base64UrlEncode(byte[] input) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(input);
    }

    private boolean constantTimeEquals(String a, String b) {
        return MessageDigest.isEqual(
                a.getBytes(StandardCharsets.UTF_8),
                b.getBytes(StandardCharsets.UTF_8)
        );
    }

    public record TokenClaims(UUID fileUploadId, String s3Key, long expiresAt, String version) {}
}
